// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.Api.DataContext;

#nullable disable

namespace TicketBooking.Api.Migrations
{
    [DbContext(typeof(TicketBookingDataContext))]
    [Migration("20221223210106_new day1")]
    partial class newday1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.Api.Entities.BookingDetails", b =>
                {
                    b.Property<Guid>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerMobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScheduleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BookingSeatDetails", b =>
                {
                    b.Property<Guid>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SeatID");

                    b.HasIndex("BookingID");

                    b.ToTable("BookingSeatDetails");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Bus", b =>
                {
                    b.Property<Guid>("BusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CoachID")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalSeat")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BusID");

                    b.HasIndex("CoachID");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BusRoute", b =>
                {
                    b.Property<Guid>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoachID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FromCityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("ToCityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RouteID");

                    b.HasIndex("CoachID");

                    b.HasIndex("FromCityID");

                    b.HasIndex("ToCityID");

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BusSchedule", b =>
                {
                    b.Property<Guid>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusID")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RouteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleID");

                    b.HasIndex("BusID");

                    b.HasIndex("RouteID");

                    b.ToTable("BusSchedules");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CityID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Coach", b =>
                {
                    b.Property<Guid>("CoachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoachName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CoachID");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.User_Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BookingDetails", b =>
                {
                    b.HasOne("TicketBooking.Api.Entities.BusSchedule", "BusSchedule")
                        .WithMany("BookingDetails")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BusSchedule");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BookingSeatDetails", b =>
                {
                    b.HasOne("TicketBooking.Api.Entities.BookingDetails", "BookingDetails")
                        .WithMany("BookingSeatDetails")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Bus", b =>
                {
                    b.HasOne("TicketBooking.Api.Entities.Coach", "Coach")
                        .WithMany("Buses")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BusRoute", b =>
                {
                    b.HasOne("TicketBooking.Api.Entities.Coach", "Coach")
                        .WithMany("BusRoutes")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBooking.Api.Entities.City", "FromCity")
                        .WithMany("FromBusRoutes")
                        .HasForeignKey("FromCityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketBooking.Api.Entities.City", "ToCity")
                        .WithMany("ToBusRoutes")
                        .HasForeignKey("ToCityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coach");

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BusSchedule", b =>
                {
                    b.HasOne("TicketBooking.Api.Entities.Bus", "Bus")
                        .WithMany("BusSchedules")
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketBooking.Api.Entities.BusRoute", "BusRoute")
                        .WithMany("BusSchedules")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bus");

                    b.Navigation("BusRoute");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.User_Role", b =>
                {
                    b.HasOne("TicketBooking.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBooking.Api.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BookingDetails", b =>
                {
                    b.Navigation("BookingSeatDetails");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Bus", b =>
                {
                    b.Navigation("BusSchedules");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BusRoute", b =>
                {
                    b.Navigation("BusSchedules");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.BusSchedule", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.City", b =>
                {
                    b.Navigation("FromBusRoutes");

                    b.Navigation("ToBusRoutes");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Coach", b =>
                {
                    b.Navigation("BusRoutes");

                    b.Navigation("Buses");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TicketBooking.Api.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
